services:

  backend:

    build: ./backend

    container_name: satellite_backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    restart: always

  frontend:
    build: ./frontend
    container_name: satellite_frontend
    ports:
      - "3000:80"
    restart: always